checkpoint_list = {
    "3dAnimationDiffusion_v10.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/3dAnimationDiffusion_v10.safetensors",
    "aZovyaPhotoreal_v2.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/aZovyaPhotoreal_v2.safetensors",
    "absolutereality_v181.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/absolutereality_v181.safetensors",
    "abyssorangemix3AOM3_aom3a1b.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/abyssorangemix3AOM3_aom3a1b.safetensors",
    "anyhentai_20.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/anyhentai_20.safetensors",
    "anyloraCheckpoint_bakedvaeBlessedFp16.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/anyloraCheckpoint_bakedvaeBlessedFp16.safetensors",
    "anyrealistic_20_25.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/anyrealistic_20_25.safetensors",
    "beautifulRealistic_v7.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/beautifulRealistic_v7.safetensors",
    "cetusMix_Whalefall2.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/cetusMix_Whalefall2.safetensors",
    "cheeseDaddys_41.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/cheeseDaddys_41.safetensors",
    "chikmix_V3.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/chikmix_V3.safetensors",
    "chilloutmix_NiPrunedFp32Fix.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/chilloutmix_NiPrunedFp32Fix.safetensors",
    "clarity_3.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/clarity_3.safetensors",
    "colorful_v80.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/colorful_v80.safetensors",
    "counterfeitV30_v30.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/counterfeitV30_v30.safetensors",
    "cyberrealistic_v42.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/cyberrealistic_v42.safetensors",
    "darkSushiMixMix_225D.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/darkSushiMixMix_225D.safetensors",
    "dreamful_v40.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/dreamful_v40.safetensors",
    "dreamshaper_8.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/dreamshaper_8.safetensors",
    "edgeOfRealism.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/edgeOfRealism.safetensors",
    "epicrealism.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/epicrealism.safetensors",
    "epicDiffusion_epicDiffusion11.safetensors" : "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/epicDiffusion_epicDiffusion11.safetensors",
    "experience_V10.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/experience_V10.safetensors",
    "ghostmix_v20.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/ghostmix_v20.safetensors",
    "hard_er.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/hard_er.safetensors",
    "hassakuHentaiModel_v13.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/hassakuHentaiModel_v13.safetensors",
    "henmixReal_v5c.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/henmixReal_v5c.safetensors",
    "icbinpICantBelieveIts_newYear.safetensors" : "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/icbinpICantBelieveIts_newYear.safetensors",
    "juggernaut_reborn.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/juggernaut_reborn.safetensors",
    "level4_v50BakedVAEFp16.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/level4_v50BakedVAEFp16.safetensors",
    "lifeLikeDiffusionV30.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/lifeLikeDiffusionV30.safetensors",
    "lofi_v4.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/lofi_v4.safetensors",
    "liberty_main.safetensors" : "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/liberty_main.safetensors",
    "majicmixRealistic_v7.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/majicmixRealistic_v7.safetensors",
    "meinamix_meinaV11.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/meinamix_meinaV11.safetensors",
    "neverendingDreamNED_v122BakedVae.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/neverendingDreamNED_v122BakedVae.safetensors",
    "onlyrealistic_v30BakedVAE.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/onlyrealistic_v30BakedVAE.safetensors",
    "perfectWorld_v6Baked.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/perfectWorld_v6Baked.safetensors",
    "photon_v1.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/photon_v1.safetensors",
    "protogenX34Photorealism.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/protogenX34Photorealism.safetensors",
    "realcartoon3d_v14.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/realcartoon3d_v14.safetensors",
    "realisian_v60.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/realisian_v60.safetensors",
    "realisticVisionV60B1_v51VAE.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/realisticVisionV60B1_v51VAE.safetensors",
    "revAnimated_v122EOL.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/revAnimated_v122EOL.safetensors",
    "rpg_v5.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/rpg_v5.safetensors",
    "stable_diffusion_15.safetensors" : "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/stable_diffusion_15.safetensors",
    "stable_diffusion_21.safetensors" : "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/stable_diffusion_21.safetensors",
    "sunshinemix_sunlightmixPruned.safetensors" : "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/sunshinemix_sunlightmixPruned.safetensors",
    "universestable_v80.safetensors" : "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/universestable_v80.safetensors",
    "xxmix9realistic_v40.safetensors" : "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/xxmix9realistic_v40.safetensors",
    }


map_checkpoint_list = {
    
    "3D Animation Diffusion": "3dAnimationDiffusion_v10.safetensors",
    "A-Zovya Photoreal": "aZovyaPhotoreal_v2.safetensors",
    "AbsoluteReality": "absolutereality_v181.safetensors",
    "AbyssOrangeMix3": "abyssorangemix3AOM3_aom3a1b.safetensors",
    "AnyHentai": "anyhentai_20.safetensors",
    "AnyLoRA": "anyloraCheckpoint_bakedvaeBlessedFp16.safetensors",
    "Beautiful Realistic Asians": "beautifulRealistic_v7.safetensors",
    "Cetus-Mix": "cetusMix_Whalefall2.safetensors",
    "Cheese Daddy's Landscapes Mix": "cheeseDaddys_41.safetensors",
    "ChikMix": "chikmix_V3.safetensors",
    "ChilloutMix": "chilloutmix_NiPrunedFp32Fix.safetensors",
    "Clarity": "clarity_3.safetensors",
    "Colorful": "colorful_v80.safetensors",
    "Counterfeit": "counterfeitV30_v30.safetensors",
    "CyberRealistic": "cyberrealistic_v42.safetensors",
    "Dark Sushi Mix": "darkSushiMixMix_225D.safetensors",
    "DreamFul": "dreamful_v40.safetensors",
    "Dreamlike Photoreal": "dreamshaper_8.safetensors",
    "DreamShaper": "dreamshaper_8.safetensors",
    "Edge Of Realism": "edgeOfRealism.safetensors",
    "Epic Diffusion": "epicDiffusion_epicDiffusion11.safetensors",
    "epiCRealism": "epicrealism.safetensors",
    "Experience": "experience_V10.safetensors",
    "GhostMix": "ghostmix_v20.safetensors",
    "HARD": "hard_er.safetensors",
    "Hassaku": "hassakuHentaiModel_v13.safetensors",
    "Henmix Real": "henmixReal_v5c.safetensors",
    "ICBINP": "icbinpICantBelieveIts_newYear.safetensors",
    "Juggernaut": "juggernaut_reborn.safetensors",
    "Level4": "level4_v50BakedVAEFp16.safetensors",
    "Liberty": "liberty_main.safetensors",
    "Life Like Diffusion": "lifeLikeDiffusionV30.safetensors",
    "LOFI": "lofi_v4.safetensors",
    "majicMIX realistic": "majicmixRealistic_v7.safetensors",
    "MeinaMix": "meinamix_meinaV11.safetensors",
    "NeverEnding Dream": "neverendingDreamNED_v122BakedVae.safetensors",
    "OnlyRealistic": "onlyrealistic_v30BakedVAE.safetensors",
    "Perfect World": "perfectWorld_v6Baked.safetensors",
    "Photon": "photon_v1.safetensors",
    "Protogen": "protogenX34Photorealism.safetensors",
    "RealCartoon3D": "realcartoon3d_v14.safetensors",
    "Realisian": "realisian_v60.safetensors",
    "Realistic Vision": "realisticVisionV60B1_v51VAE.safetensors",
    "ReV Animated": "revAnimated_v122EOL.safetensors",
    "RPG": "rpg_v5.safetensors",
    "Stable Diffusion 1.5": "stable_diffusion_15.safetensors",
    "Stable Diffusion 2.1": "stable_diffusion_21.safetensors",
    "SunshineMix＆SunlightMix": "sunshinemix_sunlightmixPruned.safetensors",
    "UniverseStable": "universestable_v80.safetensors",
    "XXMix 9realistic": "xxmix9realistic_v40.safetensors"
}

