checkpoint_list = {
    "3dAnimationDiffusion_v10.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/3dAnimationDiffusion_v10.safetensors",
    "AnythingXL_xl.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/AnythingXL_xl.safetensors",
    "aZovyaPhotoreal_v2.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/aZovyaPhotoreal_v2.safetensors",
    "absolutereality_v181.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/absolutereality_v181.safetensors",
    "abyssorangemix3AOM3_aom3a1b.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/abyssorangemix3AOM3_aom3a1b.safetensors",
    "anyhentai_20.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/anyhentai_20.safetensors",
    "anyloraCheckpoint_bakedvaeBlessedFp16.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/anyloraCheckpoint_bakedvaeBlessedFp16.safetensors",
    "anyrealistic_20_25.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/anyrealistic_20_25.safetensors",
    "beautifulRealistic_v7.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/beautifulRealistic_v7.safetensors",
    "cetusMix_Whalefall2.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/cetusMix_Whalefall2.safetensors",
    "cheeseDaddys_41.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/cheeseDaddys_41.safetensors",
    "chikmix_V3.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/chikmix_V3.safetensors",
    "chilloutmix_NiPrunedFp32Fix.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/chilloutmix_NiPrunedFp32Fix.safetensors",
    "clarity_3.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/clarity_3.safetensors",
    "colorful_v80.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/colorful_v80.safetensors",
    "counterfeitV30_v30.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/counterfeitV30_v30.safetensors",
    "cyberrealistic_v42.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/cyberrealistic_v42.safetensors",
    "darkSushiMixMix_225D.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/darkSushiMixMix_225D.safetensors",
    "dreamful_v40.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/dreamful_v40.safetensors",
    "dreamshaper_8.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/dreamshaper_8.safetensors",
    "edgeOfRealism.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/edgeOfRealism.safetensors",
    "epicrealism.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/epicrealism.safetensors",
    "experience_V10.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/experience_V10.safetensors",
    "ghostmix_v20.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/ghostmix_v20.safetensors",
    "hard_er.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/hard_er.safetensors",
    "hassakuHentaiModel_v13.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/hassakuHentaiModel_v13.safetensors",
    "henmixReal_v5c.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/henmixReal_v5c.safetensors",
    "juggernaut_reborn.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/juggernaut_reborn.safetensors",
    "level4_v50BakedVAEFp16.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/level4_v50BakedVAEFp16.safetensors",
    "lifeLikeDiffusionV30.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/lifeLikeDiffusionV30.safetensors",
    "lofi_v4.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/lofi_v4.safetensors",
    "majicmixRealistic_v7.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/majicmixRealistic_v7.safetensors",
    "meinamix_meinaV11.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/meinamix_meinaV11.safetensors",
    "neverendingDreamNED_v122BakedVae.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/neverendingDreamNED_v122BakedVae.safetensors",
    "onlyrealistic_v30BakedVAE.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/onlyrealistic_v30BakedVAE.safetensors",
    "perfectWorld_v6Baked.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/perfectWorld_v6Baked.safetensors",
    "photon_v1.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/photon_v1.safetensors",
    "protogenX34Photorealism.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/protogenX34Photorealism.safetensors",
    "realcartoon3d_v14.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/realcartoon3d_v14.safetensors",
    "realisian_v60.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/realisian_v60.safetensors",
    "realisticVisionV60B1_v51VAE.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/realisticVisionV60B1_v51VAE.safetensors",
    "revAnimated_v122EOL.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/revAnimated_v122EOL.safetensors",
    "rpg_v5.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/rpg_v5.safetensors",
    "sdXL_v10VAEFix.safetensors": "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/sdXL_v10VAEFix.safetensors",
    "sunshinemix_sunlightmixPruned.safetensors" : "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/sunshinemix_sunlightmixPruned.safetensors",
    "universestable_v80.safetensors" : "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/universestable_v80.safetensors",
    "xxmix9realistic_v40.safetensors" : "https://huggingface.co/datasets/icelabs/stable-diffusion/resolve/main/xxmix9realistic_v40.safetensors" }
